### ISSUE TITLE
while generating mat.csv file, 'm getting the following error:

### ISSUE THREAD

**Issue by rushaligupta** [githubharald/CTCWordBeamSearch#10]
File "main.py", line 33, in <module>
    res=wordBeamSearch(data.mat, 10, loader.lm, useNGrams)
  File "C:\Users\My Pc\Desktop\M.Tech Thesis Project\code\CTCWordBeamSearch-mast
er\py\WordBeamSearch.py", line 33, in wordBeamSearch
    prBlank=beam.getPrTotal()*mat[t, blankIdx]
IndexError: index 93 is out of bounds for axis 1 with size 80

_Originally posted by @rushaligupta in https://github.com/githubharald/CTCWordBeamSearch/issues/3#issuecomment-432229540_

**Comment by githubharald** [comment]
Issue not related to code of repository, therefore closing.
