### ISSUE TITLE
generation of improper mat file.

### ISSUE THREAD

**Issue by rushaligupta** [githubharald/CTCWordBeamSearch#11]
Hi,
I'm unable to generate proper mat file for my test data which would run and give me proper results. 
Once mat file is generated using the code provided, i'm getting error while running main.py file.

Can you help me to figure out what could be the possible issue?

Thanks in advance!

**Comment by rushaligupta** [comment]
this is the mat file, which i found in response to one the queries:
--------------------------------
chars = ' !"#&\'()*+,-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz' # these are the chars from IAM (file: chars.txt)
txt = 'brain.' # the text which gets encoded into the matrix
blank = len(chars) # CTC blank label gets the last label index

# size of matrix
T = 100
C = len(chars) + 1

# encode text into path
lastChar = ''
encoded = []
for t in range(T):
	if t >= len(txt):
		encoded.append(blank)
		continue
	c = txt[t]
	if lastChar == c:
		encoded.append(blank)
	encoded.append(chars.index(c))
	lastChar = c
	
print('Text', txt)
print('Path', encoded)

# create CSV
csv = ''
for t in range(T):
	for c in range(C):
		if c == encoded[t]:
			csv += '10.0'
		else:
			csv += '-10.0'
		csv += ';'
	csv += '\n'


open('mat_4.csv', 'w+').write(csv)
open('gt_4.txt', 'w+').write(txt).

-----------------

the matrix file being generated is having all entries as -10.0 . (which is not the case with given default matrix files).

-----------

error message:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    res=wordBeamSearch(data.mat, 10, loader.lm, useNGrams)
  File "C:\Users\My Pc\Desktop\M.Tech Thesis Project\code\CTCWordBeamSearch-mast
er\py\WordBeamSearch.py", line 33, in wordBeamSearch
    prBlank=beam.getPrTotal()*mat[t, blankIdx]
IndexError: index 93 is out of bounds for axis 1 with size 80



----------------------

the other files ::::


gt:   brain.
chars:    !"#&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXY[]_abcdefghijklmnopqrstuvwxyz|£§àâèéê⊥

corpus  :  brain. supposed submitt both mental and corporeal, 
the fake friend of the family like the 
is far beyond any idea

**Comment by githubharald** [comment]
OK, so there is no problem with the code of the repository?
Sorry, but I really don't have the time to debug your code. 
Therefore closing this issue.
