### ISSUE TITLE
Precondition might be too strong

### ISSUE THREAD

**Issue by jonyvp** [githubharald/CTCWordBeamSearch#17]
1. Which program causes the problem
* The C++ code of `TFWordBeamSearch`

I'm assuming the next few things:
* The `charList` is generated by the RNN, and contains all detected characters, which includes special characters like `,!#.` and so on.
* The `wordCharList` is a given by the user, denoting all characters that actually occur in words. 

The next condition is set in `TFWordBeamSearch.cpp`, lines 108-111:
```
if(!(numWordChars > 0 && numWordChars < m_numChars))
{
    throw std::invalid_argument("wordChars must contain at least one character and at least one character less than chars: 0<len(wordChars)<len(chars)");
}
```
It seems to me that numWordChars < m_numChars is enforced as m_numChars also contains non-word characters. The dataset that we use contains [a-z] only though, and so does the wordChars list ([a-z]). As such, it seems this precondition is too strong and should become:

```
if(!(numWordChars > 0 && numWordChars <= m_numChars))
```

Please correct me if I'm wrong.
Furthermore, great work on this project. Really top notch.

**Comment by weinman** [comment]
This is how the model performs multi-word recognition. (I.e., allows it to recognize when to restart the dictionary word recognition process), which of course doesn't play nicely when you only want to recognize a single word, as indicated by your wordChars list. 

I haven't thought deeply about changing the precondition as you suggest, but my way of programming around it was to insert a zero-probability character class that I then correct for after running the beam search:

```
    # CTCWordBeamSearch requires a non-word char. We hack this by
    # prepending a zero-prob " " entry to the rnn_probs
    rnn_probs = tf.pad( rnn_probs,
                        [[0,0],[0,0],[1,0]], # Add one slice of zeros
                        mode='CONSTANT',
                        constant_values=0.0 )
    chars = (' '+charset.out_charset).encode('utf8')

    # Assume words can be formed from all chars--if punctuation is added
    # or numbers (etc) are to be treated differently, more such 
    # categories should be added to the charset module
    wordChars = chars[1:]
            
    prediction,seq_prob = word_beam_search_module.word_beam_search(
        rnn_probs,
        sequence_length,
        beam_width,
        'Words', # Use No LM
        0.0, # Irrelevant: No LM to smooth
        corpus, # aka lexicon [are unigrams ignored?]
        chars,
        wordChars )
    prediction = prediction - 1 # Remove hacky prepended non-word char
```

Note that my `charset.out_charset` would be your [a-z].

**Comment by weinman** [comment]
I should add the above code uses a [forked repo](https://github.com/weinman/CTCWordBeamSearch/tree/var_seq_len) with a variable sequence length and exposing the resulting beam probability (see also #13). 

The standard code wouldn't take the `sequence_length` argument nor return the `seq_prob` value.

**Comment by githubharald** [comment]
as already explained by Jerod Weinman the characters are split into 2 sets to allow multi-word recognition (e.g. for lines containing multiple words separated by spaces, commas or other non-word-characters) .
If you only want to recognize single words (with charList==wordCharList), it makes sense to change the condition as you suggested.

**Comment by githubharald** [comment]
@jonyvp: however, I think your use-case (recognizing only single words, but constrain them to dictionary words) is very common, therefore I've changed the < operator to the <= operator.
Thanks for your input!
