### ISSUE TITLE
Error while running buildTF.sh

### ISSUE THREAD

**Issue by rushaligupta** [githubharald/CTCWordBeamSearch#18]
I'm getting the following error while running buildTF,sh file:

_buildTF.sh: [: ==: binary operator expected
Single-threaded decoding
Your TF version is 1.3.0
TF versions 1.3.0, 1.4.0, 1.5.0 and 1.6.0 are tested
buildTF.sh: syntax error near unexpected token `=('
buildTF.sh: buildTF.sh: line 52: `      TF_CFLAGS =( $( python -c 'import tensor
flow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))' ))'_

The system specifications are as follows:

OS- windows 8.1
Python: 3.5 version
Tensorflow: 1.3 version
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)

Therefore,
Not able to get 'TFWordBeamSearch.so' file.

Please help me out! Thanks in advance.

**Comment by githubharald** [comment]
TensorFlow does not support custom ops under Windows.
