### ISSUE TITLE
Creating TFWordBeamSearch.so file for custom dataset 

### ISSUE THREAD

**Issue by sirison** [githubharald/CTCWordBeamSearch#24]
@githubharald 

I'm trying to embed CTCWordBeamSearch to SimpleHTR
inorder to build TFWordBeamSearch.so file on my custom data we need to have mat_x.csv and gt_.txt file , how do I generate these file for my data, can I use the same TFWordBeamSearch.so file generated on IAM data set that is in the repository , please advise.

**Comment by githubharald** [comment]
Hi, 
you simply have to compile (see [README](https://github.com/githubharald/CTCWordBeamSearch#1-compile)) the decoder and then copy the resulting ".so" file to the src directory of SimpleHTR (see [README](https://github.com/githubharald/SimpleHTR#integrate-word-beam-search-decoding)). 
Then, call the SimpleHTR script with --wordbeamsearch parameter.
The mat and gt files are only needed for testing (i.e., you can ignore them).
