### ISSUE TITLE
Why not use unique words to build prefix tree?

### ISSUE THREAD

**Issue by SRHyd** [githubharald/CTCWordBeamSearch#26]
Hello,

Why not use unique words to build prefix tree?
 
In LanguageModel.py at line 53 
self.tree.addWords(words) # add all unique words to tree

But I think 'words' contains duplicates, shouldn't it be 'uniqueWords' ?

Thanks
SR

**Comment by githubharald** [comment]
thanks for the hint - I'll have a look at it.

**Comment by githubharald** [comment]
the tree is now created using the list of [unique words ](https://github.com/githubharald/CTCWordBeamSearch/blob/master/py/LanguageModel.py#L56)- this should speed up the building process a little bit.
