### ISSUE TITLE
How to set decode sequence length

### ISSUE THREAD

**Issue by Pay20Y** [githubharald/CTCWordBeamSearch#28]
* Custom TF operation
* TensorFlow version: 1.12.0
* Operating system: Ubuntu

How to set the sequence length parameter like in tensorflow api, thanks!

**Comment by weinman** [comment]
Per the FAQ#8, see [this fork](https://github.com/weinman/CTCWordBeamSearch/tree/var_seq_len).

**Comment by Pay20Y** [comment]
Wow thanks a lot! 
Another question please, I want to use the CTC decode based on lexicon in a single word OCR system. Parameters corpus is the lexicon (one line corresponds to one word), chars is the all characters, is this right? And what the wordChars should be?
Thanks for your patience :)

**Comment by weinman** [comment]
@Pay20Y The last bullet of point 3 in the README describes it.
    

> To be able to recognize multiple words (e.g. a text-line), the word characters must be a subset of the characters recognized by the RNN (i.e. there must be at least one word-separating character like the space character): 0<len(wordChars)<len(chars). In case only single words have to be detected, there is no need for a separating character, therefore the two parameters may also be equal: 0<len(wordChars)<=len(chars)

You might see [this usage](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/1824d71f20c1cd0bae5370e8872317f186a2cf41/src/model_fn.py#L246) (specifically starting around line 260) for an example of how I've done it.

**Comment by Pay20Y** [comment]
Thanks a lot, I will see it.
