### ISSUE TITLE
Generating the mat_x.csv

### ISSUE THREAD

**Issue by nareshr8** [githubharald/CTCWordBeamSearch#3]
Hi Team,
   Is there a way to generate mat_x.csv ourselves. i was trying to do this reading the documentation. But I was unable to find T and B values. Is there any program to generate the file. Or Can you document the procedure to do end to end testing of the application.

**Comment by rushaligupta** [comment]
while running this file, 'm getting the following error:
  File "main.py", line 33, in <module>
    res=wordBeamSearch(data.mat, 10, loader.lm, useNGrams)
  File "C:\Users\My Pc\Desktop\M.Tech Thesis Project\code\CTCWordBeamSearch-mast
er\py\WordBeamSearch.py", line 33, in wordBeamSearch
    prBlank=beam.getPrTotal()*mat[t, blankIdx]
IndexError: index 93 is out of bounds for axis 1 with size 80

**Comment by sirison** [comment]
@githubharald 

I'm trying to embed CTCWordBeamSearch to [SimpleHTR](https://github.com/githubharald/SimpleHTR)
inorder to build TFWordBeamSearch.so file on my custom data we need to have mat_x.csv and gt_.txt file , how do I generate these file for my data, can I use the same TFWordBeamSearch.so file generated on IAM data set that is in the repository , please advise.
