### ISSUE TITLE
I have compiled the TFWordBeamSearch.so on GCC 7.3.1 TF 1.5.0 and Python 3.5.2 on Linux system, when i am copying the file(.so) and keeping it in src/ folder on Windows 10, gcc 5.1.0 python 3.6.7 TF 1.5.0 , it gives me an error stating it was designed to run on windows or file not found? How do i compile it on windows for it to work here ?

### ISSUE THREAD

**Issue by Karim-Baig** [githubharald/CTCWordBeamSearch#30]
If you create a new issue, please provide the following information:

1. Which program causes the problem
* Custom TF operation
* C++ test program
* Python prototype

2. Versions
* TensorFlow version
* Python version
* C++ compiler
* Operating system

3. Issue
* Which result/error did you get?
* If you think the result is wrong - what result did you expect instead?
* How to reproduce the issue?
* Provide all necessary data, at least these files: chars.txt, wordChars.txt, corpus.txt, gt_X.txt, mat_X.csv

**Comment by githubharald** [comment]
how about reading the README?
