### ISSUE TITLE
The question about shape (TxBxC)

### ISSUE THREAD

**Issue by pvlinh143bk** [githubharald/CTCWordBeamSearch#31]
Hi Mr.Scheidl, 
I have just came into your README and I have a question. In "A First Example" section, you have mentioned about feed matrix have to be shape (TxBxC). What is the meaning of term B? 
In almost articles I read about Word Beam Search, the term B refers to Beam Width, but in your Readme, I think it's not Beam Width. 
Could you explain it for me? Thank you very much.

**Comment by githubharald** [comment]
T=sequence length
B=batch size
C=number of characters (including CTC blank)
