### ISSUE TITLE
the last word from one sentence was linked with the first word from the next sentence in LM-bigram

### ISSUE THREAD

**Issue by zzks** [githubharald/CTCWordBeamSearch#33]
Hi @githubharald , thanks for you project! 
About the python version.
when I set dataset as "bentham", I found that the last word from one sentence was linked with the first word from next sentence, and counted as bigram.

the corpus.txt of  "bentham" is:
brain. supposed submitt both mental and corporeal, 
the fake friend of the family like the 
is far beyond any idea 

and the "bigrams" shows: 
'the':{'is':2.0, 'family':2.0,'fake':2.0}

The second sentence's "the" is linked with the third sentence's "is".
I think this may effect the OCR results.
I think the correct bi-gram should be: 'the':{'family':1.0,'fake':1.0}
What do you think about this problem?
Is this a bug?

**Comment by githubharald** [comment]
I only implemented a simplified version of a LM. 
One of the limitations is that I do not take punctuation marks (like .!?) into consideration.
You can either extend the code to handle these cases, or you could look for some other open source LM and integrate it into the decoder.

Best,
Harald

**Comment by zzks** [comment]
Roger that! Thanks a lot!
