### ISSUE TITLE
Why are not used log(probabilities)?

### ISSUE THREAD

**Issue by LordOfLuck** [githubharald/CTCWordBeamSearch#36]
Thank you for this awesome repo! ;)
I was wondering why are not used log probabilities? Is the beam search stable even for long sequences?

**Comment by githubharald** [comment]
1. for my use-case (text recognition), I usually had something around 100 time-steps, for which I did not run into numerical issues
2. there already was a discussion about it, maybe the changes are already implemented in the fork, see: https://github.com/githubharald/CTCWordBeamSearch/issues/13
3. if you're comfortable with C++, it should no be too difficult to implement the changes

**Comment by LordOfLuck** [comment]
Thanks for response, I will look into the forked repo. :)

**Comment by weinman** [comment]
@LordOfLuck  FYI, I never did make any log-space changes. But as @githubharald says, the conversion process would be moderately straightforward

**Comment by LordOfLuck** [comment]
@weinman Thank you for the info, I am testing the code on long sequences now. If the decoding fails for my case, I may implement the log-space operations in the future
