### ISSUE TITLE
Unable to compile TFWordBeamSearch.so on Mac OS (Catalina)

### ISSUE THREAD

**Issue by taran21** [githubharald/CTCWordBeamSearch#38]
Hi Harald,

I am unable to compile TFWordBeamSearch.so  (Custom TF Op) on MacOS Catalina 10.15.2. Getting error as below:

ld: library not found for -l:libtensorflow_framework.1.dylib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Python version: 3.6.9
TF Version: 1.14.0

Any idea what could be wrong here. I tried adding additional MacOS flag -undefined dynamic_lookup in the g++ command that prepares the .so file. Please help.

I tried setting LIBRARY_PATH, CPPFLAGS, LDFLAGS, LD_LIBRARY_PATH but no luck yet. Anticipating best answer from your side. Thanks and have a good day. Stay safe.

**Comment by taran21** [comment]
Solved the issue. Thanks.

**Comment by thetruejacob** [comment]
How did you solve this issue?

**Comment by githubharald** [comment]
> 
> 
> How did you solve this issue?

better use the Python package installer (setup.py) instead of compiling directly for TensorFlow.
