### ISSUE TITLE
testCustomOp.py error

### ISSUE THREAD

**Issue by DucLong06** [githubharald/CTCWordBeamSearch#39]
Hi Harald
i use  : 
ubuntu 18.04
tensorflow 1.5.0
python 3.6.5
gcc version 7.5.0 
i  run  buildTF.sh done
next i run testCustomOp.py but i had a error : 
```
Mini example:
Label string: [1 0 3]
Char string: "ba"
Traceback (most recent call last):
  File "testCustomOp.py", line 92, in <module>
    testRealExample()
  File "testCustomOp.py", line 81, in testRealExample
    res = testCustomOp(mat, corpus, chars, wordChars)
  File "testCustomOp.py", line 24, in testCustomOp
    assert len(chars) + 1 == mat.shape[2]
AssertionError
```
Can you help me ?
thanks you
Long

**Comment by githubharald** [comment]
as the line numbers do not match the actual line numbers of the "assert", I guess you changed the code!? Please use exactly the version from this repo.

**Comment by DucLong06** [comment]
thank you so much
