### ISSUE TITLE
mat_0.csv | How is it created?

### ISSUE THREAD

**Issue by Tamoghna-Saha** [githubharald/CTCWordBeamSearch#42]
1. Which program causes the problem
* Python prototype

2. Versions
* Python version

3. Issue

I am trying to use more IAM validation data, but unable to understand how to get the **mat_X.csv**.

**Comment by githubharald** [comment]
you need a trained neural network, and then dump the output of the RNN layer.
It is implemented in the [SimpleHTR ](https://github.com/githubharald/SimpleHTR) repo with the --dump option (see README).
