### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by sushantag9** [githubharald/CTCWordBeamSearch#44]
If you create a new issue, please provide the following information:

1. Which program causes the problem
* Custom TF operation
* C++ test program
* Python prototype

2. Versions
* TensorFlow version : 2.2.0
* Python version : 3.7
* C++ compiler
* Operating system : Ubuntu 18.04

3. Issue
* tensorflow.python.framework.errors_impl.NotFoundError: CTCWordBeamSearch/cpp/proj/TFWordBeamSearch.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

**Comment by sdsawtelle** [comment]
For others finding this issue....

I also got `undefined symbol` errors when loading the wordbeamsearch custom operation. I resolved this by using Tensorflow 1.3 in both the `CTCWordBeamSearch` project for compiling the operation, as well as in the `simpleHTR` project. 

You can use pip to install very old, specific versions of packages using [this]() method. For instance:
` pip install --ignore-installed --upgrade https://files.pythonhosted.org/packages/7c/9f/57e1404fc9345759e4a732c4ab48ab4dd78fd1e60ee1270442b8850fa75f/tensorflow-1.3.0-cp36-cp36m-manylinux1_x86_64.whl`

I was working within a Docker image based on the `python:3.6-slim` image.
