### ISSUE TITLE
What does 'check length of chars and wordChars: 0<len(wordChars)<=len(chars)' mean?

### ISSUE THREAD

**Issue by hasansalimkanmaz** [githubharald/CTCWordBeamSearch#47]
If you create a new issue, please provide the following information:

1. Which program causes the problem
* Custom TF operation

2. Versions
* TensorFlow version: Version: 1.15.0
* Python version: 3.7
* C++ compiler: gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
* Operating system: Linux

3. Issue
I couldn't understand this error message in your code. I got this error during evalution of 1st epoch in the training.
```Batch: 1597/1597 Loss: (15.767854690551758, 0.001)
Validate NN
terminate called after throwing an instance of 'std::invalid_argument'
  what():  check length of chars and wordChars: 0<len(wordChars)<=len(chars)```


My task is to recognize handwritten dates, such as "19/10/1993" it only contains slashes and numbers. Does it result from this? 

How can I solve the issue?

**Comment by githubharald** [comment]
Hi,

can you show what you pass as chars and wordChars to the algorithm?

Just as a reminder:
* chars: all the characters that can be recognized by the neural network
* wordChars: when parsing the corpus, words are strings containing wordChars

In your case (just guessing) this could look like this: 
* chars: "/0123456789"
* wordChars: "0123456789"
* and your corpus should contain all allowed numbers like "1 2 3 \[...\] 30 31 1990 1991 \[...\] 2020 \[...\]"

So, wordChars is a subset of chars and therefore, there can't be more characters in wordChars than chars, therefore `0<len(wordChars)<=len(chars)` must hold.

**Comment by hasansalimkanmaz** [comment]
Thanks for crystal clear explanation. I will try and let you know.
