### ISSUE TITLE
Out of Dictionary prediction with specific wordbeamsearch implementation

### ISSUE THREAD

**Issue by hasansalimkanmaz** [githubharald/CTCWordBeamSearch#49]
If you create a new issue, please provide the following information:

1. Which program causes the problem
* Custom TF operation

2. Versions
* TensorFlow version == 1.15
* Python version == 3.7
* C++ compiler == 11.0.3
* Operating system == MacOS

3. Issue
I extended your SimpleHTR with word beam search. Accuracy increased 5 percent. But I see that still predictions can be out of dictionary. I know that it is possible with word beam search but I am implementing in a different way. Let me explain.

I want to recognize dates that are written in `19/10/1993` format. There are always 2 slashes. My dataset only contains the dates from `01/01/2018-31/12/2022`. This means that I have possible ~8000 targets. I treated each date as a single word then created txt files as below.

- I have added all possible outcomes as a single word to corpus.txt.
- my charlist.txt is `/0123456789`
- my wordcharlist.txt is also same `/0123456789` because slashes are in words (it is my word definition).

However, in prediction, I got  `'1/01/201'` for `10/10/2019`. I couldn't understand why I got out of dictionary result. Normally, IIUC, word beam search permits arbitrary results for the characters that don't exist in charlist.txt. Here I don't have any chars that don't exist in wordcharlist.txt

Do you have any idea where I am doing wrong?

Thanks for your repo and your effort to open source community...

**Comment by githubharald** [comment]
can you add a dump of the model output (if you're using SimpleHTR just add cmd line option --dump). 
And then only call SimpleHTR for one sample for which you get the problem.
This should create a CSV file in the dump folder.
Further, please attach the corpus file.

**Comment by hasansalimkanmaz** [comment]
Here is my `corpus.txt`.

[corpus.txt](https://github.com/githubharald/CTCWordBeamSearch/files/5354063/corpus.txt)


I already removed all unnecessary arguments for my case such as dump. Let me dump in my code.

**Comment by hasansalimkanmaz** [comment]
Here is my dump file for `10/10/2019` and got prediction '1/01/201'
[rnnOutput_0.csv.zip](https://github.com/githubharald/CTCWordBeamSearch/files/5354127/rnnOutput_0.csv.zip)

**Comment by githubharald** [comment]
I see 3 reasons:
* the optical model outputs a bad prediction. See the plot below (x-axis=chars, y-axis=timesteps). A weak signal "1" is followed by strong signal "/" at the beginning (top). And the "9" at the end only occurs as a very weak signal. So, the optical model does neither show the 10 at the beginning nor the 19 at the end very clearly. Best path decoding also just yields "1/01/201".
* there are the words "1/01/2018" and "1/01/2019" in your corpus, this is why word beam search uses them as prefix "1/01/201"
* at the end of the iteration of word beam search, the algorithm only has "1/01/201" produced as a text, but this is not yet a finished word. If there is only 1 word which has this prefix (e.g. "1/01/2018"), then the text would be auto-completed. But this is not the case in your example, as you have 2 texts with this prefix, so word beam search can't automatically decide which one to take.

![Figure_1](https://user-images.githubusercontent.com/15148095/95575993-fbd96080-0a2f-11eb-95ee-3f4faf7105f1.png)

But the main issue that I see is the poor quality of the optical model. I suggest re-training.

**Comment by hasansalimkanmaz** [comment]
Thank you very much for your crystal clear explanation, I will consider re-training. This is especially a edge case that model didn't see this type handwriting before. I expected to see the word that is defined in corpus.txt. Now, I understand why it doesn't show up.

Closing the issue.
