### ISSUE TITLE
#Issue in running Custom TF operation

### ISSUE THREAD

**Issue by jishmami** [githubharald/CTCWordBeamSearch#53]
If you create a new issue, please provide the following information:

1. Which program causes the problem
* Custom TF operation
* NumPy operation (Python package)
* C++ test program
* Python prototype

2. Versions
* TensorFlow version
* Python version
* C++ compiler
* Operating system

3. Issue
* Which result/error did you get?
* If you think the result is wrong - what result did you expect instead?
* How to reproduce the issue?
* Provide all necessary data, at least these files: chars.txt, wordChars.txt, corpus.txt, gt_X.txt, mat_X.csv

**Comment by jishmami** [comment]
Dear sir,  I can't find the file "TFWordBeamSearch.so" in the  path "../cpp/proj/TFWordBeamSearch.so". So I can't run the Custom TF operation.

**Comment by jjsr** [comment]
Hello , 
 You need to compile it yourself . And it will work only in windows in readme it is also mentioned and you may look for other closed issue as well
One thing I have tried that - I compiled .so file and copied it back on my windows but it didn't work as tf does not support custom operation . I find it after few days of trying . I know I am slow but still hopes it helped .. sorry I presumed you working on windows . If linux then you have to follow readme instructions

**Comment by githubharald** [comment]
you have to compile the C++ code first --> see README.

**Comment by jishmami** [comment]
Thank you for your response
