### ISSUE TITLE
Installing ctcwordbeamsearch decoder

### ISSUE THREAD

**Issue by zico-1** [githubharald/CTCWordBeamSearch#59]
Hi, I wish you could provide support concerning this error I am currently facing.
Using command prompt to install I always come across the error saying wheel failed to build wordbeamsearch. This is even though I have all the requirements and an updated wheel. I also have python_dev_tools installed. I have been stuck on this forever.

**Comment by githubharald** [comment]
please show the full error message + python version + operating sys.

**Comment by zico-1** [comment]
Building wheels for collected packages: word-beam-search
  Building wheel for word-beam-search (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\hp\Anaconda3\envs\GitHub\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\pi
p-req-build-706ftcqz\\setup.py'"'"'; __file__='"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-req-build-706ftcqz\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', op
en)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.cl
ose();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\hp\AppData\Local\Temp\pip-wheel-o8yk511_'
       cwd: C:\Users\hp\AppData\Local\Temp\pip-req-build-706ftcqz\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'word_beam_search' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for word-beam-search
  Running setup.py clean for word-beam-search
Failed to build word-beam-search
Installing collected packages: word-beam-search
    Running setup.py install for word-beam-search ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\hp\Anaconda3\envs\GitHub\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\
pip-req-build-706ftcqz\\setup.py'"'"'; __file__='"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-req-build-706ftcqz\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"',
open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.
close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hp\AppData\Local\Temp\pip-record-rpp6f4e4\install-record.txt' --single-version-exter
nally-managed --compile --install-headers 'C:\Users\hp\Anaconda3\envs\GitHub\Include\word-beam-search'
         cwd: C:\Users\hp\AppData\Local\Temp\pip-req-build-706ftcqz\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'word_beam_search' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\hp\Anaconda3\envs\GitHub\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\
Users\\hp\\AppData\\Local\\Temp\\pip-req-build-706ftcqz\\setup.py'"'"'; __file__='"'"'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-req-build-706ftcqz\\setup.py'"'"';f = g
etattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace
('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hp\AppData\Local\Temp\pip-record-rpp6f4e4\install-r
ecord.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\hp\Anaconda3\envs\GitHub\Include\word-beam-search' Check the logs for full comman
d output.

Using Python 3.9
OS Windows 10

**Comment by githubharald** [comment]
please read the error message. The solution is already in there.
