### ISSUE TITLE
Problem with decodings when returning the top n beams' text

### ISSUE THREAD

**Issue by mmedinajiem** [githubharald/CTCWordBeamSearch#6]
Hi!

I made some changes in the code to be able to return the top n beams from BeamList::getBestBeams. However, I'm getting now what looks to be incomplete decodings even when I'm using a dataset that was already successfully decoded with the "normal" version of TFWordBeamSearch.

For instance, with the normal version I decode a result and I get 品川区大井4-56-7, but when I try with the modified version and ask for the top 10 paths, I get this:

```
[[' 品川区大井4-56', ' 品川区大井456-', ' 品川区大井4-6-', ' 品川区大井4--6', ' 品川区大井 4-5', ' 品川区大井4-65', ' 品川区大井4-56', ' 品川区大井4-56', ' 品川区大井4-56', ' 品川区大井4-56']]
```
Nowhere in the list I can find the result I got with the original version. Now, I'm not proficient at all in C++, so probably I'm missing something. What could be causing the issue? 

EDIT: Sometimes when I'm assigning the labels to the decoded sequence I get an error because the decoded value is way higher than the total number of characters I get. I have around 4000 characters and I sometimes get a decoded value of more than 2000000.

These are the changes I made. Let me know if you'd like the whole files and how can I provide them to you.

Thank you in advance.

On WordBeamSearch.cpp

```
// Function definition (also modified on WordBeamSearch.hpp)
std::vector<std::vector<uint32_t>> wordBeamSearch(const IMatrix& mat, size_t nBestBeams, size_t beamWidth, const std::shared_ptr<LanguageModel>& lm, LanguageModelType lmType)
...
// Last part

	std::vector<std::vector<uint32_t>> bestBeamsText;
	auto bestBeams = last.getBestBeams(nBestBeams);

	for (size_t t = 0; t < nBestBeams && t < bestBeams.size(); t++)
	  {

	    // return best entry
	    auto bestBeam = bestBeams[t];
	    bestBeam->completeText();
	    bestBeamsText.push_back(bestBeam->getText());

	  }

	return bestBeamsText;
```

On TFWordBeamSearch.cpp

```
REGISTER_OP("WordBeamSearch")
.Input("mat: float32")
.Attr("nBestBeams: int")  // Added this
.Attr("beamWidth: int")
.Attr("lmType: string")
.Attr("lmSmoothing: float")
.Attr("corpus: string")
.Attr("chars: string")
.Attr("wordChars: string")
.Output("result: int32")
...

private:
  std::shared_ptr<LanguageModel> m_lm;
  size_t m_beamWidth=0;
  size_t m_numChars=0;
  size_t m_nBestBeams=1; // Added this
  LanguageModelType m_lmType=LanguageModelType::Words;


...

 // read how many beams we're going to return
	  int64 nBestBeams = 0;
	  OP_REQUIRES_OK(context, context->GetAttr("nBestBeams", &nBestBeams));
	  m_nBestBeams = static_cast<size_t>(nBestBeams);


...

// on void Compute(OpKernelContext* context) override
...
OP_REQUIRES_OK(context, context->allocate_output(0, TensorShape({B, m_nBestBeams, T}), &outputTensor));


// Inside for(int b=0; b<B; ++b)
...
// apply decoding algorithm to batch element 
			const std::vector<std::vector<uint32_t>> decoded=wordBeamSearch(mat, m_nBestBeams, m_beamWidth, m_lm, m_lmType);

			// write to output tensor
			for (size_t n=0; n < m_nBestBeams; ++n)
			  {
			    for(int t=0; t<T; ++t)
			      {
				outputMapped(b, n, t)=t<static_cast<int>(decoded.size()) ? decoded[n][t] : blank;
			      }
			  }

```

**Comment by githubharald** [comment]
1. the best beam should of course be contained in the list of the top N beams. Are using exactly the same input?
2. if you get very high values for labels, maybe you mixed unicode value (up to 2^32-1) and label value (between 0 and number of chars - 1, so at most ~4000 in your case).
3. could you fork the repo and upload your changes including at least 1 input data sample. This way I could look through it in the debugger, which is way easier to spot the error than looking through code in the comment section.

**Comment by githubharald** [comment]
should be solved after todays coding session ;-) If you have further questions just contact me directly.
