### ISSUE TITLE
CTC word beam search usage for word spotting

### ISSUE THREAD

**Issue by anofryev** [githubharald/CTCWordBeamSearch#62]
I am looking for an algorithm that i can use for effective keyword spotting on ctc-loss based nn output. 
Is there a way to use this algorithm for keyword spotting, or can you give an advice which algorithm to use for that purpose?

**Comment by githubharald** [comment]
You can of course use this algo and check if the word is contained in the output.
I'm not aware of any special algo which was developed for work spotting in CTC trained networks.
