### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Gablin31** [githubharald/CTCWordBeamSearch#65]
![image](https://user-images.githubusercontent.com/115483831/194895220-54ff511e-e785-4ea3-897c-ba19ad8bdd18.png)

**Comment by githubharald** [comment]
Hi, try with the newest pybind code, maybe there were changes in numpy.

**Comment by Lochan9** [comment]
Hi 
i did try the latest code i am still getting the same error

**Comment by githubharald** [comment]
There was a PR that I did not had time yet to check, but it might solve your issue, can you try it and let me know if it solves your issue: https://github.com/githubharald/CTCWordBeamSearch/pull/69
