### ISSUE TITLE
ImportError : undefined symbol: _ZNSt15__

### ISSUE THREAD

**Issue by allianceai** [githubharald/CTCWordBeamSearch#68]
I'm excited to start working with CTCWordBeamSearch, but I encountered this error while running the pytest after installing it.  Any insight on the below error would be greatly appreciated!
python: 3.9.7
tensorflow: 2.11.0
cuda 11.5

_______```
____ ERROR collecting tests/test_word_beam_search.py ________________
ImportError while importing test module '/home/cameron/CTCWordBeamSearch/tests/test_word_beam_search.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_word_beam_search.py:4: in <module>
    from word_beam_search import WordBeamSearch
E   ImportError: /home/cameron/anaconda3/lib/python3.9/site-packages/word_beam_search.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

**Comment by githubharald** [comment]
Hi, seems to be some mismatch between anaconda C++ libs and the ones compiled with word beam search. 

Quickly googling shows entries like these:
* https://github.com/pybind/pybind11/issues/3623
* https://stackoverflow.com/questions/67117097/c-cpython-38-x86-64-linux-gnu-so-undefined-symbol-zn6caffe28typemeta21-typem

However, I'm currently not sure how to fix this as I'm not using anaconda (but classic venv + pip).
