### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by adithyakanchan** [githubharald/CTCWordBeamSearch#7]
I tried to compile it with tenserflow-gpu version 1.3.0, but its giving **ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory** error.

System: Ubuntu 16.04, GCC 5.4, Tensorflow 1.3 GPU,CUDA 8.0,CUDNN 5.1.

Please let me know where i am going wrong?

**Comment by githubharald** [comment]
Not sure why it looks for 6.0 while you have installed 5.1 and 8.0?
Maybe the easiest work-around would be to install a CPU version of TF1.3 and compile it with this CPU version. The compiled operation should then be usable with the GPU version, too.

**Comment by githubharald** [comment]
and can you please show the complete output of buildTF.sh?
If you are using some virtual python environment, please first activate it and then execute buildTF.sh.

**Comment by adithyakanchan** [comment]
Thanks for the Quick reply.
Error was due to Tensorflow version 1.3, as per the Tensorflow documentation version 1.3 needs CUDNN 6.0.
After installing CUDNN 6.0 script complied successfully.
