### ISSUE TITLE
Error with WordBeamSearch after cloning the repo and installing dependencies

### ISSUE THREAD

**Issue by Emmybritt** [githubharald/CTCWordBeamSearch#70]
I am getting this errors after cloning the repository and installing the neccesary dependencies

================================================================================== ERRORS ==================================================================================
_____________________________________________________________ ERROR collecting tests/test_word_beam_search.py ______________________________________________________________
ImportError while importing test module '/Users/ogwuemmanuelberit/Desktop/SimpleHTR/CTCWordBeamSearch/tests/test_word_beam_search.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_word_beam_search.py:4: in <module>
    from word_beam_search import WordBeamSearch
E   ModuleNotFoundError: No module named 'word_beam_search'
========================================================================= short test summary info ==========================================================================
ERROR test_word_beam_search.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.51s =============================================================================

**Comment by githubharald** [comment]
Hi! 
Did you follow the README? Did `pip install .` work?
